config/routes.rb
Rails.application.routes.draw do

  root "homes#top"
  get "home/about" => "homes#about", as: "about"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "following" => "relationships#following"
    get "follower" => "relationships#follower"
  end
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :following

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpeg")
      profile_image.attach(io: File.open(file_path), filename: "default_image", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def followed_by?(user)
    reverse_of_relationships.exists?(following_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :config_permit_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def config_permit_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    book_comment = current_user.book_comments.new(book_comment_params)
    book_comment.book_id = @book.id
    book_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = BookComment.find(params[:id])
    book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(params[:id])
      flash[:notice] ="You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to books_path unless @user == current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follower = User.find(params[:user_id])
    following = current_user.relationships.new
    following.follower_id = follower.id
    following.save
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    following = current_user.relationships.find_by(follower_id: user.id)
    following.destroy
    redirect_to request.referer
  end

  def following
    @user = User.find(params[:user_id])
    @followings = @user.followings.all
  end

  def follower
    @user = User.find(params[:user_id])
    @followers = @user.followers.all
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]
    @search = params[:search]
    if @range == "User"
      @users = User.looks(@search, @word)
    else
      @books = Book.looks(@search, @word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment_counter.html.erb
コメント数:<%= @book.book_comments.count %>

app/views/book_comments/_comment_index.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <p><%= image_tag book_comment.user.get_profile_image(80, 80) %></p>
      <%= book_comment.user.name %>
    </td>
    <td><%= book_comment.comment %></td>
    <td><%= link_to "destroy", book_book_comment_path(book, book_comment), method: :delete, remote: true, class: "btn btn-danger btn-sm" %></td>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$("#comment_index").html("<%= j(render "book_comments/comment_index", book: @book) %>");
$(".comment_counter").html("<%= j(render "book_comments/comment_counter", book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#comment_index").html("<%= j(render "book_comments/comment_index", book: @book) %>");
$(".comment_counter").html("<%= j(render "book_comments/comment_counter", book: @book) %>");

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image(80, 80) %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <td class="favorite-<%= book.id %>"><%= render "favorites/favorite", book: book %></td>
        <td class="comment_counter"><%= render "book_comments/comment_counter", book: @book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <%= render "users/user_info", book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "index", books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render "users/user_info", book: Book.new, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_profile_image(100, 100) %><br>
              <% end %>
              <%= link_to @user.name, user_path(@user) %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td class="favorite-<%= @book.id %>"><%= render "favorites/favorite", book: @book %></td>
            <td class="comment_counter"><%= render "book_comments/comment_counter", book: @book %></td>
            <% if @book.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger btn-sm", "data-confirm" => "本当に消しますか？" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <table>
        <tbody id="comment_index">
          <%= render "book_comments/comment_index", book: @book %>
        </tbody>
      </table>

      <%= form_with model: [@book, @book_comment], local: false do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, rows: "5", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "送信" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
     <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
  <% end %>
<% end %>
<%= book.favorites.count %>

app/views/favorites/create.js.erb
$(".favorite-<%= @book.id %>").html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite-<%= @book.id %>").html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block btn-sm mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/follower.html.erb
<h1>Follower Users</h1>
<% if @followers.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>iamge</th>
        <th>name</th>
      </tr>
    </thead>
    <tbody>
      <% @followers.each do |follower| %>
        <tr>
          <td><%= image_tag follower.get_profile_image(80, 80) %></td>
          <td><%= follower.name %></td>
          <td>フォロー数:<%= follower.followings.count %></td>
          <td>フォロワー数:<%= follower.followers.count %></td>
          <td><%= link_to "Show", user_path(follower) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  ユーザーはいません
<% end %>

app/views/relationships/following.html.erb
<h1>Follow Users</h1>
<% if @followings.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>iamge</th>
        <th>name</th>
      </tr>
    </thead>
    <tbody>
      <% @followings.each do |following| %>
        <tr>
          <td><%= image_tag following.get_profile_image(80, 80) %></td>
          <td><%= following.name %></td>
          <td>フォロー数:<%= following.followings.count %></td>
          <td>フォロワー数:<%= following.followers.count %></td>
          <td><%= link_to "Show", user_path(following) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  ユーザーはいません
<% end %>

app/views/searches/_search_form.html.erb
<%= form_with url: search_path, method: :get do |f| %>
  <%= f.text_field :word %>
  <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
  <%= f.select :search, options_for_select([["完全一致", "perfect_match"], ["前方一致", "forward_match"], ["後方一致", "backward_match"], ["部分一致", "partial_match"]]) %>
  <%= f.submit "検索" %>
<% end %>

app/views/searches/search.html.erb
<% if @range == "User" %>
  <h2>Users search for "<%= @word %>"</h2>
  <%= render "users/index", users: @users %>
<% else %>
  <h2>Books search for "<%= @word %>"</h2>
  <%= render "books/index", books: @books %>
<% end %>

app/views/users/_index.html.erb
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="4"></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(80, 80) %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数:<%= user.followers.count %></td>
          <td>
            <% unless user == current_user %>
              <% if user.followed_by?(current_user) %>
                <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user), method: :post %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100, 100) %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th>
          <%= link_to user_following_path(user) do %>
            <%= user.followings.count %>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>followers</th>
        <th>
          <%= link_to user_follower_path(user) do %>
            <%= user.followers.count %>
          <% end %>
        </th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <% if user == current_user %>
      <%= link_to edit_user_path(user), class: "btn btn-block btn-outline-secondary" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% else %>
      <% if user.followed_by?(current_user) %>
        <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-info" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="user_profile_image">Image</label>
          <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render "user_info", book: @book, user: @user %>
    <%= render "index", users: @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render "user_info", book:  @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>